name: Test Build and Publish

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [main, master]

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest, macos-14-arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip and install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Install dependencies with pre-built wheels
        run: |
          pip install numpy pandas
          pip install -r requirements.txt

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist
        run: python -m build --sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/*.tar.gz

  verify_wheels:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist-artifacts

      - name: Prepare distribution files
        run: |
          mkdir -p dist
          find dist-artifacts -name "*.whl" -exec cp {} dist/ \;
          find dist-artifacts -name "*.tar.gz" -exec cp {} dist/ \;
          ls -la dist/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Verify wheel structure
        run: |
          pip install twine check-wheel-contents
          twine check dist/*
          check-wheel-contents dist/*.whl

      - name: Test package installation and imports
        run: |
          # Create test environments for each wheel
          python -m pip install virtualenv

          # Find all wheels
          for wheel in dist/*.whl; do
            echo "Testing $wheel"
            # Create a new environment for each wheel
            python -m virtualenv test-env
            source test-env/bin/activate

            # Install the wheel
            pip install $wheel

            # Try importing your package - replace 'your_package_name' with your actual package name
            python -c "import your_package_name; print(your_package_name.__version__)"

            # Deactivate and remove the environment
            deactivate
            rm -rf test-env
          done

      # Optional: Publish to TestPyPI
      # - name: Publish to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/
      #     packages-dir: dist/
      #     skip-existing: true
      #     # Use trusted publisher instead of password if possible
      #     permissions:
      #       id-token: write
      #
